### ISSUE TITLE
MacBook Pro M1 上无法打开

### ISSUE THREAD

**Issue by dgqypl** [cyhuajuan/FreeReNamer#5]
<img width="260" alt="企业微信20240524-093854@2x" src="https://github.com/cyhuajuan/FreeReNamer/assets/25171658/1074c214-9161-475a-b803-4d34fe8fd7f9">

环境：
macOS Sonoma 14.5
下载的文件：FreeReNamer_0.5.1_aarch64.dmg

操作方式：
在“应用程序”里，右键点击打开

**Comment by zhongmax** [comment]
执行这个命令
```
sudo xattr -d -r com.apple.quarantine /Applications/FreeReNamer.app
```

**Comment by dgqypl** [comment]
> 执行这个命令
> 
> ```
> sudo xattr -d -r com.apple.quarantine /Applications/FreeReNamer.app
> ```

可以了
